main: dev.peti.excavator.ExcavatorPlugin
name: Excavator
version: "1.0.0"
api-version: "1.21"
author: AUTHOR
description: DESCRIPTION
commands:
  excavator:
    description: Base command for Excavator
    usage: "/excavator give <player> <pickaxe|axe|shovel> <2x2|3x3|5x5>"
    aliases: ex
permissions:
  excavator.test:
    description: DESCRIPTION
    default: true
  excavator.*:
    description: Grants all other permissions
    default: false
    children:
      excavator.test: true
