main: dev.peti.excavator.ExcavatorPlugin
name: Excavator
version: "1.0.0"
api-version: "1.21"
author: AUTHOR
description: DESCRIPTION
commands:
  excavator:
    description: Base command for Excavator
    usage: "For a list of commands, type /excavator help"
    aliases: ex
permissions:
  excavator.test:
    description: DESCRIPTION
    default: true
  excavator.*:
    description: Grants all other permissions
    default: false
    children:
      excavator.test: true
